name: Simple Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Build Simple Docker Image
      #   run: |
      #     docker build -t simple-demo-app .

      # Uncomment below to push the image to a registry
      # - name: Docker Login
      #   run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Docker Image
      #   run: docker push simple-demo-app

  deploy:
    name: Deploy to Argo CD
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.6.0/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: ArgoCD Login
        run: |
          argocd login 192.46.232.218:30604 \
            --username admin \
            --password oo701NNXjGKEqQZc \
            --insecure --grpc-web --plaintext

      - name: Update ArgoCD Application Parameter with Timestamp
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          argocd app set etherpad \
            --parameter env.PIPELINEDEPLOYED=$TIMESTAMP

      - name: Sync ArgoCD Configmap Resource
        run: |
          argocd app sync etherpad \
            --resource apps:ConfigMap:etherpad-dev

      - name: Sync ArgoCD Deployment Resource
        run: |
          argocd app sync etherpad \
            --resource apps:Deployment:etherpad-dev
